deployment:
  kong:
    enabled: true

image:
  repository: kong/kong-gateway
  tag: "3.11"

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  cluster_dp_labels: "type:docker-kubernetesOS"
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"
  vitals: "off"
  nginx_worker_processes: "1"
  upstream_keepalive_max_requests: "100000"
  nginx_http_keepalive_requests: "100000"
  proxy_access_log: "off"
  dns_stale_ttl: "3600"
  router_flavor: expressions
  log_level: "debug"
  tracing_instrumentations: "all"
  tracing_sampling_rate: "1.0"

# Mount cluster certificates from Kubernetes secrets
secretVolumes:
  - kong-cluster-secret

# Cluster certificates are provided via Kubernetes secrets
# Each customer namespace should have a 'kong-cluster-secret' containing:
# - tls.crt: Client certificate for Kong cluster communication
# - tls.key: Private key for Kong cluster communication

admin:
  enabled: false

manager:
  enabled: false

ingressController:
  enabled: false
  installCRDs: false

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 500Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
