apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kong-dataplane
  namespace: argocd
spec:
  description: Kong DataPlane deployments for multiple customers
  sourceRepos:
    - "https://github.com/debugnin/kong-dataplane-gitops"
    - "https://charts.konghq.com"
    - "https://charts.bitnami.com/bitnami"
  destinations:
    - namespace: "kong-*"
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: networking.k8s.io
      kind: IngressClass
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: argoproj.io
      kind: Application
    - group: rbac.authorization.k8s.io
      kind: "*"
    - group: autoscaling
      kind: "*"
  roles:
    - name: admin
      policies:
        - p, proj:kong-dataplane:admin, applications, *, kong-dataplane/*, allow
      groups:
        - kong-admins
