deployment:
  kong:
    enabled: true

image:
  repository: kong/kong-gateway
  tag: "3.11"

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  cluster_dp_labels: "type:docker-kubernetesOS"
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"
  vitals: "off"
  nginx_worker_processes: "1"
  upstream_keepalive_max_requests: "100000"
  nginx_http_keepalive_requests: "100000"
  proxy_access_log: "off"
  dns_stale_ttl: "3600"
  router_flavor: expressions
secretVolumes:
  - kong-cluster-cert

admin:
  enabled: false

manager:
  enabled: false

ingressController:
  enabled: false
  installCRDs: false

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
