env:
  cluster_server_name: effeb2bded.au.cp.konghq.com
  cluster_control_plane: effeb2bded.au.cp.konghq.com:443
  cluster_telemetry_endpoint: effeb2bded.au.tp.konghq.com:443
  cluster_telemetry_server_name: effeb2bded.au.tp.konghq.com
