kong:
  deployment:
    kong:
      enabled: true
  
  image:
    repository: kong/kong-gateway
    tag: "3.6"
  
  env:
    role: data_plane
    database: "off"
    proxy_listen: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
    admin_listen: "off"
    status_listen: "0.0.0.0:8100"
  
  proxy:
    enabled: true
    type: LoadBalancer
  
  admin:
    enabled: false
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi