env:
  cluster_server_name: 995f163511.au.cp0.konghq.com
  cluster_control_plane: 995f163511.au.cp0.konghq.com:443
  cluster_telemetry_endpoint: 995f163511.au.tp0.konghq.com:443
  cluster_telemetry_server_name: 995f163511.au.tp0.konghq.com

# Use Kubernetes secret for cluster certificates
secretRefs:
  - kong-cluster-secret

envSecretRefs:
  cluster_cert:
    secret: kong-cluster-secret
    key: tls.crt
  cluster_cert_key:
    secret: kong-cluster-secret
    key: tls.key
