apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-nab
  namespace: argocd
spec:
  project: kong-dataplane
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: 18.19.4
    chart: redis
    helm:
      releaseName: redis-nab
      values: |
        auth:
          enabled: false
        master:
          persistence:
            enabled: false
        replica:
          replicaCount: 0
        metrics:
          enabled: false
        nameOverride: "nab-redis"
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-nab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true