apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-anz
  namespace: argocd
spec:
  project: kong-dataplane
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 20.2.1
    helm:
      releaseName: redis-anz
      values: |
        fullnameOverride: redis-anz
        auth:
          enabled: false
        master:
          persistence:
            enabled: true
            size: 8Gi
        replica:
          replicaCount: 0
        metrics:
          enabled: false
        resources:
          limits:
            memory: 256Mi
            cpu: 250m
          requests:
            memory: 128Mi
            cpu: 100m
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-anz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true